### ISSUE TITLE
Reflect changes introduced in RxJava 1.1.9 to PublishRelay

### ISSUE THREAD

**Issue by artem-zinnatullin** [JakeWharton/RxRelay#12]
In [RxJava 1.1.9](https://github.com/ReactiveX/RxJava/blob/1.x/CHANGES.md#version-119---august-12-2016-maven) `PublishSubject` was changed in a way to self-detect backpressure:

> Warning: the backpressure-behavior of PublishSubject has been changed. In earlier versions, when you called PublishSubject.onNext too frequently, that usually triggered a MissingBackpressureException in some downstream operator (observeOn, zip, etc.) and often it was not obvious who to blame for it. With 1.1.9, PublishSubject now tracks the request amounts of each of its children and refuses to overflow them, signalling a MissingBackpressureException to them instead which now points to the right operator.

Would be great to have same behavior in `PublishRelay`.

**Comment by JakeWharton** [comment]
Don't have time for a month or two. PRs welcome.

**Comment by JakeWharton** [comment]
At this time I'm not going to do any work on 1.x. I've branched it to `version-one` and plan to do work on 2.x only for supporting RxJava 2.x. I'll leave this open if someone else wants to make a PR. Otherwise I'll just close this in 6-12 months and mark 1.x as no longer being supported.

**Comment by artem-zinnatullin** [comment]
>At this time I'm not going to do any work on 1.x

Same here, we're planning migration to 2.x in our projects near to New Year, feel free to close.
