### ISSUE TITLE
How i can use Rxjava2 version?

### ISSUE THREAD

**Issue by ghost** [JakeWharton/RxRelay#21]
Hi, i see that you pushed RxJava2 support but i cannot find the right gradle dependency version ))

Thanks!

**Comment by JakeWharton** [comment]
It hasn't been released yet. You can use the snapshot version by adding the Sonatype snapshot repository (link in README) and using the `com.jakewharton.rxrelay2:rxrelay` maven coordinates.

**Comment by jaredsburrows** [comment]
+1
