### ISSUE TITLE
Should there be a way to atomically update the value of BehaviorRelay based on current value

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/RxRelay#24]
Was doing a toy example using a BehaviorRelay to work as a counter that could be subscribed to and had code like this to update the relay:

    count.accept(count.getValue() + 1)

And it occurred to me that code is not thread-safe. In between, the call to getValue and the call to accept some other thread could interrupt and write a new value.

I wondered if it might be a good idea to have a method like this on BehaviorRelay:

    private void updateCurrent(Function<T, T> updateFunction) {
        writeLock.lock();
        try {
            index++;
            value.lazySet(updateFunction.apply(value.get()));
        } finally {
            writeLock.unlock();
        }
    }

**Comment by JakeWharton** [comment]
All of the APIs in this project are the same as those in RxJava. So any proposals need to happen in RxJava first.

That said, a much better approach to this is to not use a relay and instead create a normal `Observable` that has this behavior. E.g.,
```java
AtomicLong count = new AtomicLong();
Observable<Long> counts = Observable.defer(() -> Observable.just(count.getAndIncrement()));
```

**Comment by dalewking** [comment]
> That said, a much better approach to this is to not use a relay and instead create a normal Observable that has this behavior. E.g.,
> 
> ```
> AtomicLong count = new AtomicLong();
> Observable<Long> counts = Observable.defer(() -> Observable.just(count.getAndIncrement()));
> ```

That was not what I was creating. It was the typical toy example of a button that updates a textview with the number of times you clicked the button, but with MVVM. So clicking the button is what increments the counts which the view subscribes to in order to update the text view.

Wasn't a definite need, just thinking out loud. In my case I just added synchronized to make it thread safe.

**Comment by JakeWharton** [comment]
That still shouldn't need to involve a relay or subject.
```
RxView.clicks(buttonView)
    .scan(0, (ignored, count) -> count + 1)
    .subscribe(countView::setText);
```

**Comment by dalewking** [comment]
Except for the part about setting it up as an MVVM example where the handling of the count is done in a viewModel, not the Activity.

**Comment by JakeWharton** [comment]
The middle operator is the view model. Observable<Actions> in,
Observable<Long> out.
