### ISSUE TITLE
checking the documentaion

### ISSUE THREAD

**Issue by bastami82** [JakeWharton/RxRelay#29]
```
// observer will receive the "one", "two" and "three" events, but not "zero"
BehaviorRelay<Object> relay = BehaviorRelay.createDefault("default");
relay.accept("zero");
relay.accept("one");
relay.subscribe(observer);
relay.accept("two");
relay.accept("three");
```

should not the comment be this instead : 
// observer will receive the "two" and "three" events, but not "zero" and "One"

**Comment by sadegh** [comment]
@bastami1982 You should use Stackoverflow for QA.

The comment is correct as the description says : `Relay that emits the most recent item it has observed and all subsequent observed items to each subscribed Observer.` which means, `BehaviorRelay` will emit the last item it has observed to each new Observer.
