### ISSUE TITLE
benefits of Relays over Subjects

### ISSUE THREAD

**Issue by feresr** [JakeWharton/RxRelay#30]
I was wondering what benefits this library brings over using subjects and avoid forwarding  `onError`/`onComplete` to them. I believe wrapping your subject inside something else like this would avoid terminal events:

```
class MyPublishRelay<I> : Consumer<I> {

    private val subject: Subject<I> = PublishSubject.create<I>()

    override fun accept(intent: I) = subject.onNext(intent)

    fun subscribe(): Disposable = subject.subscribe()
    fun subscribe(c: Consumer<in I>): Disposable = subject.subscribe(c)
    //.. OTHER SUBSCRIBE OVERLOADS
}
```

I might be missing something, I'm not an expert and I'm asking this just to learn more :)

**Comment by JakeWharton** [comment]
Subjects have far more overhead because they have to track and handle
terminal event states. Relays are stateless aside from subscription
management.

Also your type doesn't implement Observable as Relays do, and incurs the
cost of the additional allocation and indirection.
