### ISSUE TITLE
How to delay accept() ?

### ISSUE THREAD

**Issue by mladenrakonjac** [JakeWharton/RxRelay#31]
I would like to call accept() after some time. Is it possible?

**Comment by JakeWharton** [comment]
Relays are bridges between the non-reactive world and reactive world. If you want to delay an event, you either need to do it in the non-reactive world (threads, handlers, executors) or in the reactive world (delay, throttle, sample operators). It cannot be done at the bridge.

**Comment by mladenrakonjac** [comment]
Is this good? 
 Completable.complete().delay(2, TimeUnit.SECONDS).doOnComplete(() -> eventRelay.accept(3L));

Cause I am not getting event

**Comment by JakeWharton** [comment]
No. You are not subscribing to that completable which means it's not going to run.

The idea of using a completable to post an even to a subject isn't very idiomatic Rx. In that example you could return `Observable.just(3L).delay(2, SECONDS)` instead of the subject and achieve the same effect.
