### ISSUE TITLE
Nullable Annotation for getValue methods in BehaviorRelay/ReplayRelay

### ISSUE THREAD

**Issue by bangarharshit** [JakeWharton/RxRelay#36]
I am not sure if library follows the policy `ParametersAreNonnullByDefault` but if it is it will be great if `Nullable` annotations can be added to the required methods for code analysis tools. Currently, there are no `Nullable` annotations except - `jdk.internal.jline.internal.Nullable`.   

I can send a PR if it is ok.

**Comment by JakeWharton** [comment]
Feel free. It should match your RxJava PR exactly.

**Comment by bangarharshit** [comment]
Thanks. I will open a PR. It also needs an update in RxJava as `Nullable` annotation was introduced in a later version.
