### ISSUE TITLE
ReplayRelay buffer size does not change after timeout

### ISSUE THREAD

**Issue by Wosin** [JakeWharton/RxRelay#38]
When using _createWithTime()_, even if the time expires the _buffer_ size does not change and there is no elegant way to check if there are any values that are not expired in the buffer, since _hasValue()_ returns
 _buffer.size() != 0_. I've read that this behaviour is the expected one as it matches the behaviour of _ReplaySubject_. But creating a method that allows for elegant checking for unexpired values would be quite nice idea I think.

**Comment by JakeWharton** [comment]
Does this happen with ReplaySubject as well?

**Comment by Wosin** [comment]
Hey, 
It does not happen with the ReplaySubject. I think that it's not the desired behaviour of the ReplaySubject. I have made a quick PR to fix that: https://github.com/JakeWharton/RxRelay/pull/39

**Comment by Wosin** [comment]
Any updates on this ??

**Comment by JakeWharton** [comment]
Is your PR a port of the code inside ReplaySubject? I don't remember seeing
a change to it in RxJava but I might have missed something.

**Comment by Wosin** [comment]
Yeah,
That's how ReplayBuffer looks like now: https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/subjects/ReplaySubject.java
Feel free to verify it :)
