### ISSUE TITLE
NonNull annotations on static factory methods for improved Kotlin interop

### ISSUE THREAD

**Issue by benwicks** [JakeWharton/RxRelay#40]
I'm using this library in a Kotlin project. I have a line like:
`private val myRelay = BehaviorRelay.createDefault("Default value")`

The type of `myRelay` is inferred as `BehaviorRelay<String!>!`. Can this project use annotations to make the type be inferred as `BehaviorRelay<String>` on such static factory methods?

Looking at #37, we could use `io.reactivex.annotations` to mark return types on methods such as `BehaviorRelay.createDefault` as `NonNull`.

I'm not sure how to annotate the method signature to say that the generic type is non null.

**Comment by JakeWharton** [comment]
The best you'll get out of this is `BehaviorRelay<String!>`, unfortunately.

**Comment by JakeWharton** [comment]
Anyway, PR welcome.

**Comment by benwicks** [comment]
Do you know if it's possible to cause Kotlin to infer that `b` is a `Boolean` and not a `Boolean?`?
```
val myRelay = BehaviorRelay.createDefault(true)
val a = myRelay.hasValue()
val b = myRelay.value
if (a && b) { // This won't compile since b is a nullable "Boolean?"
  // ...
}
```

**Comment by JakeWharton** [comment]
No. The library is written in Java and so there's no way to track
nullability through type parameters.
