### ISSUE TITLE
PublishRelay leaking

### ISSUE THREAD

**Issue by d3bt3ch** [JakeWharton/RxRelay#42]
I am using PublishRelay in our custom AlertDialogFragment to return results of the button selected. Upon recieveing the event on my sbscribe method i am dismissing the dialog fragment. PublishRelay is leaking in such a situation. What am i doing wrong ?

**Comment by JakeWharton** [comment]
This isn't an RxRelay-specific question. The same thing happen with a `PublishSubject`. I would encourage you to ask on the RxJava mailing list or on StackOverflow with the 'rx-java' tag for more visibility.
