### ISSUE TITLE
Allow Subscribe to only buffered values

### ISSUE THREAD

**Issue by aunger** [JakeWharton/RxRelay#52]
My team would like to subscribe to only the past/buffered values of a ReplayRelay.  Thank you for providing `getValues()`, but we wish to use the Observable API.  Here's our current (Kotlin) solution:

```kotlin
relay.take(relay.values.size.toLong()).subscribe { /* do something */ }
````

...but the array copy in `getValues()` is a little wasteful to merely get the buffer size.

Would it be OK to add `ReplayRelay::getBufferedCount` or even `ReplayRelay::takeBuffered`?

**Comment by aunger** [comment]
I can work up an implementation PR if you wish.

**Comment by JakeWharton** [comment]
If you can get these APIs added to RxJava's Subjects then they can be added here. Otherwise I'm not open to changing the API in a way that provides functionality not provided by subjects.

**Comment by aunger** [comment]
Oops, I overlooked the fact this is exactly the ReplaySubject API.

BTW, I appreciate your careful maintenance here and your other FOSS. Our code has benefited from your work. Thank you.
