### ISSUE TITLE
Behavior Relay accept Nullable Type in Kotlin

### ISSUE THREAD

**Issue by springwong** [JakeWharton/RxRelay#54]
Is it possible that BehaviorRelay accept nullable type in kotlin and pass null in accept() or createDefault()?
`val relay: BehaviorRelay<String?> = BehaviorRelay.createDefault(null)`
or
`relay.accept(null)`

Now, it will throw NullPointerException if pass any null value into BehaviorRelay.

**Comment by JakeWharton** [comment]
RxJava 2 Subjects are not tolerant of nulls and so Relays are not tolerant of them either. You would never be able to propagate the null to any subscriber anyway since the RxJava internals also would prevent you.
