### ISSUE TITLE
RxJava 3 support

### ISSUE THREAD

**Issue by dariuszseweryn** [JakeWharton/RxRelay#55]
Are there any plans for it?

**Comment by JakeWharton** [comment]
Nothing urgent. Once stable is out I'll update the group, packages, and
imports and do a release. As far as I've seen, nothing interesting is
happening with subjects in 3.x so there's no work to do here either.

**Comment by dariuszseweryn** [comment]
I am currently updating `RxAndroidBle` to `RxJava 3` and it is depending on `RxRelay` so I am blocked. No big deal — just adding for the context.

I will leave this issue open — feel free to close it once RxJava 3 support will be added (I will get a notification)

Best regards

**Comment by JakeWharton** [comment]
I'll take a PR if you're willing to depend on a snapshot in the mean time.
I don't want to be releasing ahead of stable though.

**Comment by dariuszseweryn** [comment]
> I don't want to be releasing ahead of stable though.

Naturally

> I'll take a PR if you're willing to depend on a snapshot in the mean time.

I will see what I can do, depending on how time I will have

**Comment by j-garin** [comment]
@JakeWharton stable version is out
