### ISSUE TITLE
RxRelay convert to Single, Maybe.

### ISSUE THREAD

**Issue by a23sokolov** [JakeWharton/RxRelay#61]
Hello, thank you for your lib! 

Is there an appropriate way to convert RxRelay in Single, Maybe.
Observable default methods like `firstElement/lastElement/firstOrError/astOrError` aren't appropriate for this situation, cuz Complete/Error skipped for Relay.

Example:
```
val relay = BehaviorRelay.create<String>()
relay.lastElement()
    .defaultIfEmpty("some string")
    .subscribe ({
        Timber.d("it = $it")
    }, Timber::e)
```

RxRelay -> **nothing** is printed
Observable -> "some string" will be printed 

P.S. Also you can work with RxRelay like Observable. On other layers, you don't know what hiding under Observable. This can lead to errors

**Comment by JakeWharton** [comment]
Relays are infinite so anything depending on a "last" element will never work. Your only option is to use a first or indexed operator to pull a specific value, or to use a subject which you can send a complete event to.

Infinite observables can be created without using relays, so knowledge of whether an observable completes is an implicit contract that at best should be documented by the abstraction which provides the observable.
