### ISSUE TITLE
Question: how can BehavioralRelay value be nullable?

### ISSUE THREAD

**Issue by ericntd** [JakeWharton/RxRelay#62]
Version: 2.1.0
RxJava: 2.2.6

Since the default value is always there and not null
```java
/**
     * Constructs a BehaviorRelay with the given initial value.
     * @param defaultValue the initial value, not null (verified)
     * @throws NullPointerException if {@code defaultValue} is null
     */
    BehaviorRelay(T defaultValue) {
        this();
        if (defaultValue == null) throw new NullPointerException("defaultValue == null");
        value.lazySet(defaultValue);
    }
```

and `accept(value)` doesn't accept null either
```java
@Override
    public void accept(T value) {
        if (value == null) throw new NullPointerException("value == null");

        setCurrent(value);
        for (BehaviorDisposable<T> bs : subscribers.get()) {
            bs.emitNext(value, index);
        }
    }
```

How can the value ever be null? 🙏  🤔 
```java
/**
     * Returns a single value the Relay currently has or null if no such value exists.
     * <p>The method is thread-safe.
     */
    @Nullable
    public T getValue() {
        return value.get();
    }
```

I don't see anywhere `value.lazySet` or `value.set` or `value =` is used in BehavioralRelay.java where it could cause the value to be missing either
Hence couldn't answer my own question

How I use BehavioralRelay
```kotlin
val myRelay :BehavioralRelay<Int> = BehavioralRelay.createDefault(0)
//...
val latestValue = myRelay.value
// do stuffs with the latest value
```

**Comment by oldergod** [comment]
What's the default value when you do `BehaviorRelay.create()` ?

**Comment by ericntd** [comment]
hi @oldergod , it's 0
Also updated my question with how I use BehavioralRelay

**Comment by JakeWharton** [comment]
Looks like an accidental holdover from reducing the RxJava `BehaviorSubject` sources: https://github.com/ReactiveX/RxJava/blob/24df131ecc012aa0591b9123b79a1f0f6a14a4f9/src/main/java/io/reactivex/subjects/BehaviorSubject.java#L320-L327

Feel free to send a PR to change it!

**Comment by JakeWharton** [comment]
Like @oldergod said, if you call `create()` the value will be null until one is supplied so the annotation is correct.

**Comment by carstenhag** [comment]
@JakeWharton Aren't the [release notes](https://github.com/JakeWharton/RxRelay/blob/master/CHANGELOG.md) confusing/misleading then? I thought "Fix: Change `BehaviorRelay#getValue` return type to be non-nullable." would mean that BehaviorRelay#getValue now has a `@NonNull` annotation, but it doesn't:

https://github.com/JakeWharton/RxRelay/blob/master/src/main/java/com/jakewharton/rxrelay3/BehaviorRelay.java#L152
