### ISSUE TITLE
Discussion on why the need for RxRelay should diminish as your code becomes more reactive over time

### ISSUE THREAD

**Issue by ZakTaccardi** [JakeWharton/RxRelay#7]
> As more of your code moves to reactive, the need for Subjects and Relays should diminish.

I am working to make my code more reactive (specifically my UI, my backend is already fully reactive), so I would love further explanation of this.

**Comment by JakeWharton** [comment]
A subject is an escape hatch in/out of a stream for non-reactive code. As more of your code becomes reactive (i.e., represented as observables) then you don't need these escape hatches, and can instead use the built-in primitives (like `flatMap`, etc.) to compose things together.

**Comment by ZakTaccardi** [comment]
I see a Subject/Relay as an Rx-version of an EventBus. Specifically something that would enable the lifecycle/eventbus architechure mentiod in [Yigit's Android Application Architecture talk](https://youtu.be/BlkJzgjzL0c?t=9m5s):
- onStart(): register for events, load data
- onStop(): unregister from events

This architecture provides two significant advantages:
1. Multiple subscribers can request the same event simultaneously without repeating the loading sequence. See this [gist](https://gist.github.com/ZakTaccardi/3b455be24f5ca39684a82aec9a713eaa) for example
2. Unsubscribing from events does not interrupt the loading sequence (while an Rx unsubscription does). Think of a LoginActivty with a poor Rx implementation. User taps "Log In" button, immediately rotates the device (`onStop()` causing an Rx unsubscription), and the user never gets logged in.

I definitely prefer the more type-safe nature of reactive observables - but how can you address the above 2 issues without using a Subject/RxRelay?

**Comment by JakeWharton** [comment]
> Multiple subscribers can request the same event simultaneously without repeating the loading sequence
> 
> Unsubscribing from events does not interrupt

Neither are true with `.publish().autoConnect()`

**Comment by ZakTaccardi** [comment]
do you disagree with the recommended practice that utilizes a Subject from the [Where Reactive Rubber Meets the Road talk](https://www.youtube.com/watch?v=va1d4MqLUGY)? Or [Brad Campbell's article summarizing it](http://blog.bradcampbell.nz/keep-your-main-thread-synchronous/)

This seems like an ideal use-case for `RxRelay` (although I'm not yet sure how to propagate errors downstream, which `RxRelay` does not support because of the observable contract)

EDIT: see [Dan Lew's talk at Droidcon](https://youtu.be/QdmkXL7XikQ?t=35m10s) on how to handle expected errors

**Comment by JakeWharton** [comment]
Of course. There's no need to use a subject to accomplish that.

**Comment by ZakTaccardi** [comment]
How can you accomplish it without using a Subject/Relay?

**Comment by JakeWharton** [comment]
Use an Observable

**Comment by williamwebb** [comment]
> > Multiple subscribers can request the same event simultaneously without repeating the loading sequence
> 
> Unsubscribing from events does not interrupt
> Neither are true with .publish().autoConnect()

@JakeWharton I assume this would this require storing the original observable in a instance object for subsequent requests to then call .publish().autoConnect() on? Or is there a better way to obtain this behavior?

**Comment by ZakTaccardi** [comment]
>  I assume this would this require storing the original observable in a instance object for subsequent requests to then call .publish().autoConnect() on? 

If a tree falls in the woods and no one has a variable reference to it, does anyone hear it?

But yes, you need to store a reference to it. Here's an example of what I'm doing:

```
if (loginAttemptObservable == null) {
            loginAttemptObservable = loginNetwork.getLoginAttempt(signInRequest)
                    .doOnSuccess(loginAttempt -> userDb.writeUser(loginAttempt.user()))
                    .doOnSuccess(loginAttempt -> currentUser = loginAttempt.user())
                    .subscribeOn(io)
                    .observeOn(main)
                    .doOnSuccess(this::updateLoginAttempt)
                    .toObservable()
                    .publish()
                    .autoConnect()
                    .doAfterTerminate(() -> loginAttemptObservable = null)
            ;
        }

        loginAttemptObservable.subscribe(
                ignore -> {
                },
                throwable -> Timber.e(throwable, "Error logging in")
        );
```

notice the `.loginAttemptObservable = null`. This should null out the reference so the observable is recreated once it terminates. There may be a better way to do this though

**Comment by djodjoni** [comment]
interesting discussion but going a bit off topic :)
@JakeWharton back to the initial statement:

> As more of your code becomes reactive (i.e., represented as observables) then you don't need these escape hatches, and can instead use the built-in primitives (like flatMap, etc.) to compose things together.

The 'escape hatches' might be achieved without using Subject or Relays but any custom observable created from any source or callback. Also Subjects/Relays do not only have onNext but are able to subscribe to Observables :) which means you have reactive code on both sides and Subjects/Relays are just the "reactive middle man".

Even if you only have observables coming in and be able to merge and compose things in magical ways you may not have all the sources(observables) at the moment of a subscription thus any further source that pops up needs to identify itself to all the interested parties and thus all the merge and composition magic along with subscriptions needs to happen again to include the newcomer.

Again the use I see is more like an Rx publish–subscribe pattern implementation and the idea is to use Subjects/Relays as a proxy so subscribers can receive events without knowledge of which publishers, if any, there are, while maintaining clear connection between event producers and event consumers, unlike many eventbus implementations out there.

**Comment by JakeWharton** [comment]
I have yet to see an example of subscribing a Subject or Relay to a stream that wasn't and anti-pattern.

**Comment by djodjoni** [comment]
why subscribing a Subject or Relay to a stream should be immediately an anti-pattern ?

i'll try to give a simple example.
suppose we have 2 separate presenters. 
P1 holds a View with a Button. 
P2 hold a view to display info.

Scenario 1:  No Relays 
1) P1 receives call to send Network Request
2) P1 sends Request and gets an Observable form the Network Module
3) P1 send the observable to P2 
4) P2 subscribes to it 
5) P2 receives an event and renders data
...

Scenario 2: With Relays
0) P2 subscribes to a Relay "XX" (happens only once)
1) P1 receives call to send Network Request
2) P1 sends Request and gets an Observable form the Network Module
3) P1 subscribes Relay "XX" to the Observable 
4) P2 receives an event and renders data
...

Sure, here we do not have that much advantage especially that Relays/Subjects are the vulnerable(mutable) part in the chain, but lets suppose we take care of that.

Now what if we have many P1 and many P2 it can become a mesh of passing Observables around and this doesn't look too reactive to me.

So is Scenario 2 an anti-pattern in your opinion?

**Comment by JakeWharton** [comment]
Yes. Just expose the Observable in P1 that flatMaps the clicks into
requests to P2.

**Comment by djodjoni** [comment]
well in that case I might need to expose the full state of P1 as well, as it might be important for building the request, which will essentially lead to a merge of P1 and P2, not even mentioning that there might me more P1s and P2s.. but this is not the question.
The question is why  Scenario 2 is an anti-pattern :)

**Comment by JakeWharton** [comment]
Then those state things should be modeled in streams instead.

**Comment by djodjoni** [comment]
an option as well, but still I don't see how this is a better solution its just more coupled and also not convinced why subscribing a Subject or Relay to a stream is an anti-pattern.

Anyway thanks for the discussion and the lib :)

**Comment by kailash09dabhi** [comment]
Hello Jake Wharton!
 First of all thanking you as i use many stuffs created by you! :)

Now, I am using RxBus for UI events and this seems good library but in the README file you said about this issue that " RxRelay should diminish as your code becomes more reactive over time". So I wanted to know how can i replace RxBus code the reactive approach then? any examples?

**Comment by JakeWharton** [comment]
Whenever you publish an event into your bus, change the code to expose an
Observable. Whenever you listen to an event from the bus, change the code
to subscribe to the Observables you have exposed.

**Comment by ZakTaccardi** [comment]
> I wanted to know how can i replace RxBus code the reactive approach then? any examples?

Relays are mutable, which is why they should be avoided where possible. I like to synchronize my apps around a reactive database.

Imagine you have a data source - a list of e-mails. maybe this is a table in your database. Have your data layer expose this as an `Observable<List<Email>>`. The act of subscribing to this observable could kick off a network job (via `doOnNext` maybe) that will update the email database table upon success. Because your UI is observing the email table, the UI gets notified.

**Comment by kailash09dabhi** [comment]
@JakeWharton Ok Thanks for this suggestion i must choose this way then and will try to implement it. :)
But Is there any example out there to follow?
As I am not sure still as how to implement it.

**Comment by ZakTaccardi** [comment]
if anyone is still confused as to why the need for subjects/relays should diminish over time, check out Kaushik Gopal's talk on multi-casting.

https://academy.realm.io/posts/360-andev-2017-kaushik-gopal-rxjava-by-example-multicasting/

tl;dr: you can use the multicasting operators to avoid using subject/relays

**Comment by JakeWharton** [comment]
I don't think that's a comprehensive recommendation since more often
subjects and relays are used to bridge non-reactive code. The tl;dr is get
your data sources to be stream-based and not callback-based and then you're
free to compose them with normal operators–some of which are the multicast
ones.

**Comment by cebaa** [comment]
@JakeWharton 

> I have yet to see an example of subscribing a Subject or Relay to a stream that wasn't and anti-pattern.

Isn't any case of inter-dependent observables a good choice for these?

E.g. consider a game of [Nim](https://en.wikipedia.org/wiki/Nim). Each player plays after the first played and their move depends on the previous move of their opponent. So it's 2 `Observable<Move>` instance that depend on each other. 

How would you structure this only in terms of stream-based flows? I don't think I've seen an example of this case so far, so if there's one it might be good to link it here.

**Comment by JakeWharton** [comment]
I think you're conflating where state is held vs. how state is propagated. Nothing about the game needs encoded into the shape of the streams. For that you only need a type which exposes an observable of the game state and has methods which make moves.

**Comment by cebaa** [comment]
@JakeWharton 

> For that you only need a type which exposes an observable of the game state and has methods which make moves.

Let's introduce GameStateManager for that purpose. That means that: 

- Each Player (and everything else that needs to change the game state) is now coupled to GameStateManager 
- The stream is broken at Player - GameStateManager boundary
- State is now kept in GameStateManager and is not in streams anymore

In fact, GameStateManager looks to me like (a very limited version) of Subject that just breaks the uniformity of using streams everywhere in your application and doesn't bring anything to the table.

What is the benefit of GameStateManager or a drawback of Subject in this scenario?

**Comment by JakeWharton** [comment]
It's far more powerful than a subject because it doesn't require encoding
your entire application logic as massive compositions of Rx operators.
Doing so is an anti-pattern and you'll wind up in a hell where your
application state is implicitly spread throughout a giant Rx chain instead
of encapsulated into semantic types with Rx only being used for propagation
of that state.

**Comment by guelo** [comment]
If I may revive this discussion, I agree with the idea of moving the stream all the way to the data source. But at the source itself I don't see the need to get rid of Subjects/Relays. `subject.onNext()` and `relay.accept()` are much cleaner and easier to reason about APIs than `Observable.create()` or the other ways of creating sources. Especially for hot streams. I don't see the need to ever get rid of them there.
