### ISSUE TITLE
How to pass both values and errors?

### ISSUE THREAD

**Issue by danielesegato** [JakeWharton/RxRelay#8]
The examples provided show how to give results to Observers by doing:

`relay.call(data);`

With an Observable as source you use it as an Action:

`observable.subscribe(relay);`

then somewhere I can:

`return relay.asObservable();`

to receive all the events, so far so good.

But I would like to receive both the success values and the errors, is there any way?

**Comment by JakeWharton** [comment]
What errors are you talking about? A relay will never error.

**Comment by danielesegato** [comment]
I'm looking for a way of having an Observable emitting values and errors without ever stopping the observer subscribtion.

A sequence like this:

onNext
onNext
onError
onNext
onError

should be valid.

It looks like onError is always considered with an ending condition (aka = always followed by onComplete), I was hoping RxRelay could help me in that.

**Comment by JakeWharton** [comment]
That is not possible and would violate the RxJava contract. Instead, use a type which abstracts the success and error case into a single type which can be passed through `onNext`. These are sometimes called "either" types.

**Comment by danielesegato** [comment]
@JakeWharton yes, same conclusion I read everywhere :) but that's not the same thing. An error goes through the Observable chain, skipping filters, mapping etc allowing you to do a catch-like handling.

Even when implementing retry and retryWhen, it would be useful to be able to get that error reach the UI. I'm still a beginner at reactive programming, but I can't understand this limitation

Thanks, I guess I'll figure something out.

**Comment by JakeWharton** [comment]
A catch block doesn't allow you to resume the statements in a try block.

**Comment by danielesegato** [comment]
@JakeWharton this is the difference between:

```
try {
  for () {
    stuff();
  }
} catch(e) {}
```

and

```
for () {
  try {
    stuff();
  } catch(e) {}
}
```

except time is involved in the loop, each transformation happens on the single element / event and _could_ be catched on the single element.

I still would like to transform the stuff I "loop" upon, filter it, but being able to catch errors on the single events blocking the chain for THAT event.

With Rx it seems like I can replicate the first case but not the second.

**Comment by JakeWharton** [comment]
The second case is re-subscribing to the stream when onError occurs.

**Comment by danielesegato** [comment]
@JakeWharton are you talking about `onErrorResumeNext()` or actually calling `subscribe()` again in the onError handler?

I couldn't find a way of achieving what RxRelay does (suppress onComplete + allow multiple subscriptions) and keep errors so that I can use resumeNext (in any of those ways).

BehaviorRelay does exactly what I need in the case no error happens. But if an error happens I would like the error to reach my Observers and, at the same time, keep the BehaviorRelay "alive" and ready to relay other values.

If I do not use Relay I can do the error handling but after the first onComplete() I can't subscribe again, would create an infinite loop (immediate onComplete again)

**Comment by mkonicek** [comment]
@danielesegato I'm using the `retry` method to achieve what you're describing. Actually I didn't need RxRelay, just using `PublishSubject` from RxJava 1:

```
addToUnsubscribe(view.onFavoriteClicked()
                .flatMap(ignored ->
                        favoriteArticlesRepository.flipFavorite(article, view.getContext())
                                .subscribeOn(ioScheduler))
                .observeOn(uiScheduler)
                .retry((nRetries, e) -> {
                    Log.e("MyApp", "Cannot update article favorite status", e);
                    // On error, re-subscribe and continue receiving click events
                    return true;
                })
                .subscribe(updatedIsFavorite -> view.showIsFavorite(updatedIsFavorite)));
```
